# Generated by Django 2.2.24 on 2022-03-15 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paggle_home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='result',
            name='score',
        ),
        migrations.AddField(
            model_name='result',
            name='confusion_matrix',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='result',
            name='metric_results',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
