# Generated by Django 2.2.24 on 2022-01-04 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paggle_home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ham10000_image',
            old_name='dataset_id',
            new_name='dataset',
        ),
    ]
