# Generated by Django 2.2.24 on 2022-02-18 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paggle_home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ML_Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True)),
                ('description', models.TimeField(blank=True)),
                ('imports', models.TextField(blank=True)),
                ('c_dataset', models.TextField(blank=True)),
                ('f_preprocess', models.TextField(blank=True)),
                ('f_createModel', models.TextField(blank=True)),
                ('f_train', models.TextField(blank=True)),
                ('f_test', models.TextField(blank=True)),
            ],
        ),
        migrations.AlterField(
            model_name='result',
            name='model',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='paggle_home.ML_Model'),
        ),
        migrations.DeleteModel(
            name='Model',
        ),
    ]
