# Generated by Django 2.2.24 on 2022-02-18 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paggle_home', '0002_auto_20220218_0858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ml_model',
            name='c_dataset',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='ml_model',
            name='description',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='ml_model',
            name='f_createModel',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='ml_model',
            name='f_preprocess',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='ml_model',
            name='f_test',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='ml_model',
            name='f_train',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='ml_model',
            name='imports',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='ml_model',
            name='name',
            field=models.TextField(),
        ),
    ]
