# Generated by Django 2.2.24 on 2022-02-18 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paggle_home', '0003_auto_20220218_0902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ml_model',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
