# Generated by Django 2.2.24 on 2022-02-18 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paggle_home', '0004_auto_20220218_0906'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ml_model',
            old_name='c_dataset',
            new_name='createModel_function',
        ),
        migrations.RenameField(
            model_name='ml_model',
            old_name='f_createModel',
            new_name='dataset_class',
        ),
        migrations.RenameField(
            model_name='ml_model',
            old_name='f_preprocess',
            new_name='preprocess_function',
        ),
        migrations.RenameField(
            model_name='ml_model',
            old_name='f_test',
            new_name='test_function',
        ),
        migrations.RenameField(
            model_name='ml_model',
            old_name='f_train',
            new_name='train_function',
        ),
    ]
