# Generated by Django 2.2.24 on 2021-12-08 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paggle-home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='link',
            field=models.TextField(blank=True),
        ),
    ]
